apiVersion: v1
kind: Secret        
metadata:
  name: mysql-secret 
  namespace: petvida-k8s
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootadmin
  MYSQL_DATABASE: petvida
  MYSQL_USER: pet_admin
  MYSQL_PASSWORD: senha123